name: Create Release
on:
  pull_request:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  version: ${{ github.ref_name }}
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Set Spark Connector version to tag version
        run: sed -i 's|ThisBuild / version := ".*$|ThisBuild / version := "${{ env.version }}"|' build.sbt
      - name: Run integration test to ensure release works
        run: sbt -v +test
      - name: Create jar with all dependencies included
        run: |
          sbt assembly
          test -f ./target/scala-2.12/weaviate-spark-connector-assembly-${{ env.version }}.jar
      - name: Create Release only if tag v* was pushed
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          generateReleasenotes: true
          name: Release ${{ env.version }}
          artifacts: "./target/scala-2.12/weaviate-spark-connector-assembly-${{ env.version }}.jar"
          artifactContentType: application/java-archive
